export const providerIconIds: Record<string, string> = {
	Akamai: "akamai",
	"AWS CloudFront": "aws-cloudfront",
	"AWS S3": "aws-s3",
	Azure: "azure",
	"Azure App Service": "azure",
	"Azure Front Door": "azure",
	"Azure Blob Storage": "azure",
	"Azure Static Web Apps": "azure",
	Cloudflare: "cloudflare",
	"Cloudflare Pages": "cloudflare-pages",
	DigitalOcean: "digitalocean",
	Discourse: "discourse",
	Fastly: "fastly",
	Firebase: "firebase",
	"Fly.io": "fly",
	Framer: "framer",
	Ghost: "ghost",
	GitBook: "gitbook",
	GitHub: "github",
	"GitHub Pages": "github",
	"Google Cloud": "google-cloud",
	"Google Cloud Storage": "google-cloud",
	Heroku: "heroku",
	HubSpot: "hubspot",
	Mintlify: "mintlify",
	Netlify: "netlify",
	Railway: "railway",
	ReadMe: "readme",
	Render: "render",
	Shopify: "shopify",
	Squarespace: "squarespace",
	Substack: "substack",
	Vercel: "vercel",
	Webflow: "webflow",
	Wix: "wix",
};
