export const providerIconIds: Record<string, string> = {
	Akamai: "akamai",
	"AWS CloudFront": "aws-cloudfront",
	"AWS S3": "aws-s3",
	"Bunny CDN": "server",
	CDN77: "server",
	Imperva: "server",
	KeyCDN: "server",
	Medianova: "server",
	Sucuri: "server",
	"Tencent EdgeOne": "server",
	"Azure App Service": "azure",
	"Azure Front Door": "azure",
	"Azure Blob Storage": "azure",
	"Azure Static Web Apps": "azure",
	Cloudflare: "cloudflare",
	"Cloudflare Pages": "cloudflare-pages",
	"Cloudflare Workers": "cloudflare",
	"DigitalOcean App Platform": "digitalocean",
	Discourse: "discourse",
	Fastly: "fastly",
	Firebase: "firebase",
	"Fly.io": "fly",
	Framer: "framer",
	Ghost: "ghost",
	GitBook: "gitbook",
	"GitHub Pages": "github",
	"Google Cloud": "google-cloud",
	"Google Cloud Run": "google-cloud",
	"Google Cloud Storage": "google-cloud",
	"Google Front End": "google-cloud",
	Heroku: "heroku",
	"Hostinger CDN": "server",
	HubSpot: "hubspot",
	Mintlify: "mintlify",
	Netlify: "netlify",
	Railway: "railway",
	ReadMe: "readme",
	Render: "render",
	Shopify: "shopify",
	Squarespace: "squarespace",
	Substack: "substack",
	Vercel: "vercel",
	Webflow: "webflow",
	Wix: "wix",
};
